shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zoxide]
github = "ajeetdsouza/zoxide"
hook = "source ~/.zoxide.zsh"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.forgit]
github = "wfxr/forgit"

[plugins.zsh_codex]
github = "tom-doerr/zsh_codex"
